# -*- Makefile -*-
# Make rules for configuration files.
#

CFG             = kernel-$(VERSION)
KCONFIG		= python kconfig.py --merge
KARCH		= $(shell uname -m)

CONFIGFILES     = $(CFG)-$(KARCH).config $(CFG)-$(KARCH)-debug.config

OLDCONFIG	?= olddefconfig

GCC_VER		= gcc10-
make_defines 	= CC=$(GCC_VER)gcc HOSTCC=$(GCC_VER)gcc HOSTCXX=$(GCC_VER)g++ LD=$(GCC_VER)ld.bfd

config: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) kernel-$(VERSION)*config

kernel-$(VERSION)-x86_64.config: config-x86_64
	@echo "# x86_64" > $@
	@cat $^ >> $@

kernel-$(VERSION)-x86_64-debug.config: config-x86_64-debug
	@echo "# x86_64" > $@
	@cat $^ >> $@

kernel-$(VERSION)-aarch64.config: config-aarch64
	@echo "# arm64" > $@
	@cat $^ >> $@

kernel-$(VERSION)-aarch64-debug.config: config-aarch64-debug
	@echo "# arm64" > $@
	@cat $^ >> $@

NEWCONFIGS	= $(addprefix configs/,$(CONFIGFILES))

configs :
	@mkdir -p $@

$(NEWCONFIGS) : configs/% : % configs
	@cp -v $< .config
	Arch=$$(head -1 .config | cut -b 3-) ; make ARCH=$$Arch $(OLDCONFIG) $(make_defines); echo "# $$Arch" >$@ ; cat .config >>$@

newconfigs: $(NEWCONFIGS)
